### ISSUE TITLE
Visualization image upside down issue

### ISSUE THREAD

**Issue by susiefeng** [phildong/minian#22]
All visualized images in pipeline are upside down compare with original data. Adding inverted Y axis to fix this.
![pull](https://user-images.githubusercontent.com/47085209/53261804-f1275780-36a2-11e9-9952-d7d631ae1c63.PNG)
**I'll make a pull request once I finish preprocessing and pulling your new changes..**

**Comment by phildong** [comment]
fixed in 98a71f28c7d9c168692c5e5f94946ad8eaf96e82
