### ISSUE TITLE
demo movie origin

### ISSUE THREAD

**Issue by DenisPolygalov** [phildong/minian#3]
Hi @phildong 
it will be very helpful if you drop few lines of text about where is your demo movie came from.
I've noticed two things:
1. The frame size is not the MIniscope's default 752 x 480. Was it resized? If so - what was the resizing method used?
2. The calcium activity in the movie is very slow comparing to my previous experience. I guess this might be because your recording is from barin area I'm not familiar with. Where is it? Another reason might be that the frame rate is very high (higher that written in the actual file). Another possibility of the slow activity is some bug in my code. Unfortunately I can not open your avi file in my Media Player Classic in order to do code-independent frame rate test - it just crashes. Here is output from my code:
https://ibb.co/yY708kn

Regards,
Denis.

**Comment by phildong** [comment]
Hi Denis,
Sorry for the belated reply!
Yes the video was down-sampled to accommodate github's 100MB file size limit. I used ffmpeg to do the down-sampling http://ffmpeg.org/ffmpeg-filters.html#scale
The recording was done in dorsal CA1 at 30 frames per second, despite whatever the video metadata says. I believe the miniscope DAQ software always write to a 20 fps avi no matter what actual recording frame rate you used, hence the confusion. I tried to make no assumptions of frame-rate in my analysis and let the user specify those time-related parameters. The video plays fine with vlc but unfortunately I don't have Windows to test for mpc, but I think it should be fine to serve as a demo as long as the data itself is not corrupted. Let me know if you have more questions!

**Comment by DenisPolygalov** [comment]
I see... Unfortunately using ffmpeg makes it useless for any kind of analysis. Well, in our case. Other people may think differently of course.. 

> I believe the miniscope DAQ software always write to a 20 fps avi no matter what actual recording frame rate you used, hence the confusion.

the above is wrong. At least on Windows. I checked it in details. By counting bytes in each frame. 
The software programed Miniscope camera to 20 FPS at launch, but GUI shows 30 FPS - this is simple misplacement of items in the GUI's list box. Changing FPS values in the list box correctly re-program camera to correspondent FPS.
