### ISSUE TITLE
Run into error in stripe correction

### ISSUE THREAD

**Issue by susiefeng** [phildong/minian#7]
![screen shot 2019-01-30 at 11 07 11 pm](https://user-images.githubusercontent.com/47085209/52030060-00701680-24e4-11e9-8936-2adeeab516a8.png)
![screen shot 2019-01-30 at 11 07 18 pm](https://user-images.githubusercontent.com/47085209/52030071-08c85180-24e4-11e9-8b21-6ee686f8c835.png)

**Comment by phildong** [comment]
fixed by e3a7d5b928c2ea3a8f2746e0313322fd0adf5c2f closing.
