### ISSUE TITLE
Visualization tool bar gets cut off when data being modified in height/width 

### ISSUE THREAD

**Issue by susiefeng** [phildong/minian#8]
When cut off like 150 pixels of original videos, tool bar got cut off in the following visualization steps.
![v_bug](https://user-images.githubusercontent.com/47085209/52183047-027ef180-27d2-11e9-818b-0087fd8e1696.PNG)

**Comment by phildong** [comment]
by default the visualization tools make one label/coordinate on either height/width dimension correspond to one pixel on your screen. If that's too small, try increasing `output_size` and make sure to put it in effect by running `hv.output(size=output_size)` after that. Feel free to re-open if this doesn't fix your issue!
